title: Gaming Crew Vienna
description: Board Games • People • Community
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

include:
    - _pages
    - .htaccess

author:
  name: Gaming Crew Vienna
  links:
    - label: 'Instagram'
      icon: 'fab fa-instagram'
      url: 'https://instagram.com/gamingcrew.vienna'

    

